#!/bin/bash  
#SBATCH --mail-user=echao8@ucmerced.edu # REPLACE WITH YOUR EMAIL
#SBATCH --mail-type=ALL  
#SBATCH -p short
#SBATCH -t 2:00:00
#SBATCH --ntasks-per-node=56
#SBATCH --output=../logs/convert_hf_checkpoint%j.stdout 
#SBATCH --job-name=convertCheckpoint
#SBATCH --export=ALL


whoami

module load anaconda3

source /home/scratch/echao8/finetune/bin/activate 

python ../scripts/convert_hf_checkpoint.py --model_path DAMO-NLP-SG/VideoLLaMA3-2B --save_path ../weights/videollama3_2b_local