#!/bin/bash  
#SBATCH --mail-user=echao8@ucmerced.edu # REPLACE WITH YOUR EMAIL
#SBATCH --mail-type=ALL  
#SBATCH -p cenvalarc.gpu #test
#SBATCH -t 30:00:00
#SBATCH --ntasks-per-node=56
#SBATCH --output=../logs/postProc_5000im_3e_%j.stdout 
#SBATCH --job-name=postproc
#SBATCH --export=ALL
#SBATCH --gres=gpu:1

whoami

module load anaconda3

source /home/scratch/echao8/finetune/bin/activate 

module load ffmpeg
module load gcc/9.3.0


# uncomment for the right requirements

# pip install flash_attn --no-build-isolation
# pip install transformers==4.46.3 accelerate==1.0.1
# pip install decord ffmpeg-python imageio opencv-python
# pip install torch 
# pip install openai

# Run your Python script

python ../scripts/postProcessing.py